# Generated by Django 4.2.5 on 2023-10-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personality', '0002_profile_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='images/avatars/avatar.jpeg', upload_to='images/avatars/'),
        ),
    ]
