# Generated by Django 4.2.5 on 2023-10-12 12:55

from django.db import migrations, models
import django_app.utils


class Migration(migrations.Migration):

    dependencies = [
        ('personality', '0004_profile_monster_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='monster_counter',
            field=models.JSONField(default=django_app.utils.get_default_dict),
        ),
    ]
