# Generated by Django 4.2.5 on 2023-10-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personality', '0007_alter_profile_monster_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='monster_counter',
            field=models.JSONField(default=dict),
        ),
    ]
