# Generated by Django 4.2.5 on 2023-10-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='image',
            field=models.ImageField(default=None, upload_to='images/monsters/'),
            preserve_default=False,
        ),
    ]
