# Generated by Django 4.2.5 on 2023-10-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monster', '0002_monster_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='image',
            field=models.ImageField(default=None, upload_to='images/monsters/'),
        ),
    ]
