# Generated by Django 4.2.5 on 2023-10-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monster', '0003_alter_monster_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='description',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='monster',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/monsters/'),
        ),
    ]
