# Generated by Django 4.2.5 on 2023-11-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monster', '0005_monstercounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='monstercounter',
            name='wealth',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
